[package]
name = "roguelike-tutorial"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
license = "WTFPL"
readme = "README"

[dependencies]
tcod = { version = "0.9", features = ["rustc-serialize"] }
rustc-serialize = "0.3"
rand = "0.3"
