[package]
name = "roguelike-tutorial"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
license = "WTFPL"
readme = "README"

[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs"
features = ["rustc-serialize"]

[dependencies]
rustc-serialize = "0.3.15"
rand = "0.3.9 "
